package algogenetico;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JFrame;

/**
 *
 * @author tania
 */
public class Interfaz extends javax.swing.JFrame {
   public int tamPob, generaciones;
   public String cadena;
   public static String primPob, ultPob;
   public AlgoritmoGenetico ag;
   public Poblaciones poblaciones;
   /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setTamPob(int n){
      this.tamPob = n;
    }

    public int getTamPob(){
      return this.tamPob;
    }

    public void setCadenaEncon(String cad){
      this.cadena = cad;
    }

    public String getCadenaEncon(){
      return this.cadena;
    }

    public void setGeneraciones(int g){
        this.generaciones = g;
    }
    public int getGeneraciones(){
        return this.generaciones;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        lblCadena = new javax.swing.JLabel();
        jtfCadena = new javax.swing.JTextField();
        btnInicia = new javax.swing.JButton();
        jtaPoblacion = new java.awt.TextArea();
        lblPob = new javax.swing.JLabel();
        lblApt = new javax.swing.JLabel();
        jtaAptitud = new java.awt.TextArea();
        jtaSeleccion = new java.awt.TextArea();
        lblSel = new javax.swing.JLabel();
        lblTamPob = new javax.swing.JLabel();
        jtfTamPob = new javax.swing.JTextField();
        jtaCruza = new java.awt.TextArea();
        lblCruza = new javax.swing.JLabel();
        btnLimpia = new javax.swing.JButton();
        lblGeneracion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblElMejor = new javax.swing.JLabel();
        jtfGeneraciones = new javax.swing.JTextField();
        lblElBest = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        lblGenActual = new java.awt.Label();
        btnMostEv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Algoritmo genético baby");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        p2.setBackground(new java.awt.Color(204, 204, 255));

        lblCadena.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCadena.setText("Cadena:");

        jtfCadena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCadenaKeyReleased(evt);
            }
        });

        btnInicia.setText("Inicia");
        btnInicia.setEnabled(false);
        btnInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaActionPerformed(evt);
            }
        });

        jtaPoblacion.setEditable(false);

        lblPob.setText("Población");

        lblApt.setText("Aptitud");

        jtaAptitud.setEditable(false);

        jtaSeleccion.setEditable(false);

        lblSel.setText("Selección");

        lblTamPob.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTamPob.setText("Tamaño de la Población:");

        jtfTamPob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTamPobKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTamPobKeyTyped(evt);
            }
        });

        jtaCruza.setEditable(false);

        lblCruza.setText("Cruza");

        btnLimpia.setText("Limpiar");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        lblGeneracion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblGeneracion.setText("Generaciones:");

        jLabel2.setText("El mejor:");

        jtfGeneraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfGeneracionesActionPerformed(evt);
            }
        });
        jtfGeneraciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfGeneracionesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfGeneracionesKeyTyped(evt);
            }
        });

        jLabel3.setText("Generación actual:");

        btnMostEv.setText("Mostrar Progreso");
        btnMostEv.setEnabled(false);
        btnMostEv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostEvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblPob)
                .addGap(159, 159, 159)
                .addComponent(lblApt)
                .addGap(154, 154, 154)
                .addComponent(lblSel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCruza)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(jtaPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jtaAptitud, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jtaSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jtaCruza, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p2Layout.createSequentialGroup()
                        .addComponent(lblCadena)
                        .addGap(12, 12, 12)
                        .addComponent(jtfCadena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTamPob, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTamPob, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGeneracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p2Layout.createSequentialGroup()
                                        .addGap(317, 317, 317)
                                        .addComponent(lblElMejor))
                                    .addGroup(p2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblGenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addComponent(btnInicia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpia))
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(lblElBest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostEv)))))
                .addGap(32, 32, 32))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamPob)
                    .addComponent(jtfTamPob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeneracion)
                    .addComponent(jtfGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadena))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblApt)
                        .addComponent(lblPob)
                        .addComponent(lblSel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblCruza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtaCruza, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtaSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtaAptitud, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtaPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInicia)
                            .addComponent(btnLimpia)
                            .addComponent(lblElMejor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblElBest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostEv))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTamPobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTamPobKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (Character.isDigit(c) && jtfTamPob.getText().startsWith("0"))) {
            evt.consume();
        }
        if(c == '.' &&  jtfTamPob.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfTamPobKeyTyped

    private void jtfTamPobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTamPobKeyReleased
        // TODO add your handling code here:
                // TODO add your handling code here:
        boolean ver = false;
        if(jtfCadena.getText().equals("") || jtfTamPob.getText().equals("") || jtfGeneraciones.getText().equals("")){
            ver = false;
        }else{
            ver = true;
        }
        btnInicia.setEnabled(ver);
    }//GEN-LAST:event_jtfTamPobKeyReleased

    private void jtfCadenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCadenaKeyReleased
        // TODO add your handling code here:
                // TODO add your handling code here:
        boolean ver = false;
        if(jtfCadena.getText().equals("") || jtfTamPob.getText().equals("") || jtfGeneraciones.getText().equals("")){
            ver = false;
        }else{
            ver = true;
        }
        btnInicia.setEnabled(ver);
    }//GEN-LAST:event_jtfCadenaKeyReleased

    private void btnIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaActionPerformed
      int tam = Integer.parseInt(jtfTamPob.getText());
      int nGen = Integer.parseInt(jtfGeneraciones.getText());
      if(tam==0 || nGen==0){
       JOptionPane.showMessageDialog(null, "el tamaño de la población y el numero de generaciones no pueden ser 0", "Error", JOptionPane.ERROR_MESSAGE);
      }else{
        jtfTamPob.setEnabled(false);
        String cad = jtfCadena.getText();
        jtfCadena.setEnabled(false);
        jtfGeneraciones.setEnabled(true);
        ag = new AlgoritmoGenetico(tam, cad, nGen);
        ag.inicializa();
      }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciaActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        // TODO add your handling code here:
        btnMostEv.setEnabled(false);
        jtaAptitud.setText("");
        jtaPoblacion.setText("");
        jtaCruza.setText("");
        jtaSeleccion.setText("");
        jtfCadena.setText("");
        jtfCadena.setEnabled(true);
        jtfTamPob.setText("");
        jtfTamPob.setEnabled(true);
        btnInicia.setEnabled(false);
        jtfGeneraciones.setText("");
        jtfGeneraciones.setEnabled(true);
        lblElBest.setText("");
        lblGenActual.setText("");

    }//GEN-LAST:event_btnLimpiaActionPerformed

    private void jtfGeneracionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGeneracionesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (Character.isDigit(c) && jtfTamPob.getText().startsWith("0"))) {
            evt.consume();
        }
        if(c == '.' &&  jtfTamPob.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfGeneracionesKeyTyped

    private void jtfGeneracionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGeneracionesKeyReleased
        // TODO add your handling code here:
        boolean ver = false;
        if(jtfCadena.getText().equals("") || jtfTamPob.getText().equals("") || jtfGeneraciones.getText().equals("")){
            ver = false;
        }else{
            ver = true;
        }
        btnInicia.setEnabled(ver);
    }//GEN-LAST:event_jtfGeneracionesKeyReleased

    private void jtfGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGeneracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfGeneracionesActionPerformed

    private void btnMostEvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostEvActionPerformed
        // TODO add your handling code here:
        poblaciones = new Poblaciones(new JFrame(), true, primPob, ultPob);
        poblaciones.setVisible(true);
    }//GEN-LAST:event_btnMostEvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicia;
    private javax.swing.JButton btnLimpia;
    public static javax.swing.JButton btnMostEv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static java.awt.TextArea jtaAptitud;
    public static java.awt.TextArea jtaCruza;
    public static java.awt.TextArea jtaPoblacion;
    public static java.awt.TextArea jtaSeleccion;
    private javax.swing.JTextField jtfCadena;
    private javax.swing.JTextField jtfGeneraciones;
    private javax.swing.JTextField jtfTamPob;
    private javax.swing.JLabel lblApt;
    private javax.swing.JLabel lblCadena;
    private javax.swing.JLabel lblCruza;
    public static java.awt.Label lblElBest;
    public static javax.swing.JLabel lblElMejor;
    public static java.awt.Label lblGenActual;
    private javax.swing.JLabel lblGeneracion;
    private javax.swing.JLabel lblPob;
    private javax.swing.JLabel lblSel;
    private javax.swing.JLabel lblTamPob;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    // End of variables declaration//GEN-END:variables
}
